#!/bin/sh

OS=${OS:-unix}

ocaml setup.ml -configure --enable-${OS}
ocaml setup.ml -build

if [ "$1" = "true" ]; then
  ocamlfind remove io-page-${OS} || true
  ocaml setup.ml -install
elif [ "$1" = "test" ]; then
  ocaml setup.ml -configure --enable-unix --enable-tests
  ocaml setup.ml -build
  ocaml setup.ml -test
fi
